### ISSUE TITLE
Disabling Zoom turns OSD invisible on analog display

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/PokemonMini_MiSTer#1]
Using an Analog IO board with a 15khz analog display, the core no longer shows OSD menu if Zoom option is disabled. Switching the option on brings the menu back. The core itself functions properly with Zoom disabled, as if it is running with 1x zoom option.

**Comment by Grieverheart** [comment]
This is indeed the case, and the reason why I provide the ability to either enable or disable the Zoom. On a CRT, if Zoom is not enabled, the drawing area is too small to display the OSD. When Zoom is enabled, I instead add black bars allowing the OSD to display.

**Comment by Thelypody** [comment]
How about renaming the Zoom option to something like "240p Mode" for additional clarity then? That's what Atari Lynx core calls its 2x zoom option. This way a potential user might better understand what the option is intended for and getting issues after disabling it might make them understand why they shouldn't play with it.
