### ISSUE TITLE
Audio crackle issue and shrill sounds

### ISSUE THREAD

**Issue by ajgowans** [MiSTer-devel/PokemonMini_MiSTer#2]
There is a noticeable crackle on the core, you can hear it as the first sound when launching Pokemon Party on the splash.  You don't hear this on original hardware.  The audio is also very shrill in the core, which it is not when played through the little speaker on the console - it might be worth trying to add some filtering to it to smooth it off.  I could try get a recording of my device if it would help, although I don't have a terribly good microphone to hand currently.  

Note I am using the BIOS: [BIOS_Nintendo_Pokemon_Mini_World.min]4.00 KB
Attached is a raw audio recording made of my actual device playing Pokemon Party, audio was so low it has been boosted significantly so has a lot of background noise sadly, but may be of some use as a reference. 

[Pokemon Mini - Polemon Party - Raw Recording 1.wav.zip](https://github.com/MiSTer-devel/PokemonMini_MiSTer/files/9500793/Pokemon.Mini.-.Polemon.Party.-.Raw.Recording.1.wav.zip)

**Comment by KremlingKuthroat19** [comment]
A good comparison to test the audio could also be the Bad Apple homebrew demo. Here are two videos of the original hardware vs the MiSTer core for comparison:

Original Hardware: https://www.youtube.com/watch?v=Jr_pVfFXcrk

MiSTer: https://www.youtube.com/watch?v=B4Xz64ylwJ8

You'll notice there's a lot more crackling on MiSTer
